config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :users

  resources :posts do
    resources :comments
  end

  get '/login' => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true, length: {maximum: 30}
  validates :password, presence: true, length: {minimum: 8}
  has_many :posts
  has_many :comments
  # has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.find(params[:id])
  end
  # Create a new Comment
  def new
    @comments = Comment.new
  end
  # Get the post ID and create a comment under that post.
  # Redirect to the post you commented on.
  def create
    @post = Post.find(params[:post_id])
    @comments = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end
  # Edit the comment. Find the post that the comment belogs to. Find the comment
  #  id of that post.
  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end
  # Update the comment you edited. If successful redirect back to post.
  # Else show the edit page again.
  def update
    @post = Post.find(params[:post_id])
    @comments = @post.comments.find(params[:id])
    if @comments.update(comment_params)
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end
# Delete Comment and redirect back to post.
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
   def comment_params
     params.require(:comment).permit(:commenter)
   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user= User.all
    @post = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

 # Grab all Post
  def index
    @posts = Post.all
  end
# Find ampost by id
  def show
    @post = Post.find(params[:id])
  end
# Create new post
  def new
    @post = Post.new
  end
  # If creation successful redirect to the user's account else render "New".
  def create
    @post = Post.new(post_params)
    @post.user_id = session[:user_id]
    if @post.save
      redirect_to user_path(session[:user_id])
    else
     render 'new'
    end
  end
# Find pot to edit by id.
  def edit
    @post = Post.find(params[:id])
  end
# Update the post information. If successful redirect user to User Account else
# render the edit page.
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to user_path(session[:user_id])
    else
      render 'edit'
    end
  end
# Find post by ID and delete. Redirect to the posts show page.
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(session[:user_id])
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end
#  If username entered is equal to the username entered under new session log_in
# user and redirect to their account. Else flash alert error and redirect to login page.
  def create
    @user = User.where(username: params[:session][:username]).first
    if @user.password == params[:session][:password]
      session[:user_id]=@user.id
      log_in @user
      puts "my sess = #{session[:user_id]}"
      redirect_to @user
    else
      flash[:alert] = "Invalid Username/Password. Please try again"
      redirect_to login_path
    end
  end
# When user signs out set the session id to nil and redirect user to Login Page.
  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def current_user
    @current_user = User.find_by_id(session[:user_id])
  end
  def index
    @user = User.all
  end

  def new
    @user = User.new
  end
  # Create new user. If saved successfully flash 'Welcome to SoapBox'. Set the current session
  # to user.id. Else flash error and redirect user to signUp again.
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to SoapBox"
      session[:user_id] = @user.id
      redirect_to @user
      puts "the current session is #{session[:user_id]}"
    else
      flash[:alert] = "Oops! Something went wrong. Try again!"
      redirect_to new_user_path
    end
  end
# Display Specific user information
  def show
    @user = User.find(params[:id])
    @post = @user.posts
  end
# Find specific user and delete account. Redirect to Home page.
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to "/"
  end

 # method that defines what the required parameters are for user.
  private
  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  # sets current user
  def current_user
     @current_user ||= User.find_by(id: session[:user_id])
   end
  #Checks to see if current user is logged in- for links
  def logged_in
    !current_user.nil?
  end

  def log_out(user)
    current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<%= form_for([@post, @comment]) do |form| %>
  <div id="commenteditContainer">
      <%= form.text_area :commenter, :placeholder => "User", :class=> "editcommentTitle"  %>
      <%= form.submit "Save Comment", :class => "editcommentSubmit"%>
  </div>
<% end %>

<%= link_to 'Back', post_path(@post.id), :class => "backUser" %>
<%= link_to 'Delete Comment',[@comment.post, @comment], method: :delete,
data: { confirm: 'You are about to delete your comment. Continue?' }, :class => "deletecomment"%>

app/views/home/index.html.erb
<h3 id="home_phrase">Let Fly the Fury of Your Words</h3>
<p id="homeCategories"> Read Salty Angst </p>
<div id="homeContainer">
    <% @post.each do |post| %>
        <p id="home_post">
          <%= link_to post.title, post_path(post), :id => "view_post" %>
        </p>
        <hr id="home_hr">
    <% end %>
</div>
<%=image_tag("salty_land.png", :class => "saltyL") %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title>Salty</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
      <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah|Roboto:500" rel="stylesheet"
    </head>
    <a id="home" href="/">Home</a>
    <% if logged_in %>
        <%= link_to "Log Out", logout_path,  method: :delete , :class => "logout" %>
        <%= link_to "Your Account", user_path(session[:user_id]), :class => "account" %>
    <% else %>
        <%= link_to "SignUp", new_user_path , :class => "signup" %>
        <%= link_to "LogIn", login_path , :class => "login"%>
    <% end %>
    <nav>
      <%=image_tag("shaker.png", :id => "shakey") %>
      <%=image_tag("fallingsalt.png", :id => "falling") %>
      <p id="nav_header">Salty</p>
    </nav>
    <body>
      <% if flash[:notice] %>
        <%= flash[:notice] %>
      <% end %>
      <% if flash[:alert] %>
        <%= flash[:alert] %>
      <% end %>

      <%= yield %>

    </body>
  </html>

app/views/posts/edit.html.erb
<div class="posteditform">
  <%= form_for :post, url: post_path(@post), method: :patch do |post| %>
    <p>
      <%= post.text_field :title, :placeholder => "Title", :class=> "postTitle" %>
    </p>
    <p>
      <%= post.text_area :content, :placeholder => "Body", :class=> "postBody"  %>
    </p>
    <p>
      <%= post.submit "Save Post", :class => "postSubmit" %>
    </p>
  <% end %>
</div>

<%= link_to 'Back to Account',user_path(session[:user_id]), :class => "backUserEdit" %>
<%= link_to "Delete Post", post_path,  method: :delete,
data: { confirm: 'You are about to delete your post. Continue?' }, :class => "deletepostEdit" %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <p><strong> <%= post.title %> </strong></p>
  <p>
    <%= link_to "View", post_path(post) %> |
    <%= link_to "Edit", edit_post_path(post) %>
    <%= link_to "Delete", post_path(post),method: :delete,
    data: { confirm: "You are about to delte this post. Would you like to continue?"} %>
  </p>
 <% end %>

app/views/posts/new.html.erb
<div class="posteditform">
  <%= form_for :post, url: posts_path do |post| %>
    <p id="haters"> Salt Thy Haters</p>
    <p>
      <%= post.text_field :title, :placeholder => "Title", :class=> "postTitle" %>
    </p>
    <p>
      <%= post.text_area :content, :placeholder => "Body", :class=> "postBody" %>
    </p>
    <p>
      <%= post.submit "Post", :class => "postSubmit"  %>
    </p>
  <% end %>
  </div>
  <%= link_to 'Back to Account',user_path(session[:user_id]), :class => "backUser" %>

app/views/posts/show.html.erb
<div id="postContainer">
  <p id="thepostTitle">
    <%= @post.title %>
  </p>
  <p id="thepostContent">
    <%= @post.content %>
  </p>
  <h3 id="comments">
    Comments
  </h3>
  <% @post.comments.each do |comment| %>
    <p id="userCommentsTitle">
      <%= comment.commenter %>
    </p>
        <%= link_to 'Edit Comment', edit_post_comment_path(@post, comment), :class => "editComment" %>
  <% end %>
  <h3 id="addComment">
    Add a comment:
  </h3>
  <%= form_for([@post, @post.comments.build]) do |form| %>
    <p>
      <%= form.text_area :commenter, :placeholder => "Comment",:class=> "commentTitle" %>
    </p>
    <p>
      <%= form.submit "Save Comment", :class => "commentSubmit" %>
    </p>
  <% end %>

  <% if session[:user_id] == @post.user_id %>
    <%= link_to "Delete Post", post_path, method: :delete,
    data: { confirm: 'You are about to delete your post. Continue?' }, :class => "deletepost" %>
    <%= link_to 'Back to Account',user_path(current_user), :class => "backUser" %>
  <% end %>
</div>

app/views/users/index.html.erb
<p>All Users </p>
<% @user.each do |user| %>
<li>
  <%= user.username %>
  <%= link_to "View Account", user_path(user.id) %>
  <%= link_to "Delete Account", users_path,  method: :delete %>
</li>
<% end %>

app/views/users/new.html.erb
<div id="signupform">
  <h1 id="signuptext">
    Unleash Your Seasoning
  </h1>
  <%= form_for :user, url: users_path do |user| %>
    <%= user.text_field :username, :placeholder => "Username", :id => "signupUsername" %>
    <%= user.text_field :password, :placeholder => "Password", :id => "signupPassword" %>
    <%= user.submit "Sign Up", :id => "signupSubmit" %>
  <% end %>
</div>
<%=image_tag("salty_land.png", :class => "saltyL") %>

app/views/users/show.html.erb
<div id="accountbackground"></div>

<div id="accountInfo">
  <h1 id="userAccount">
    <%=@user.username %>'s Salt Box
  </h1>
</div>
<!--For each post made by user display post title and content  -->
<% @post.each do |post| %>
  <div id="accountPost">
    <p id="ptitle">
      <%= post.title %>
    </p>
    <p id="pcontent">
      <%= post.content%>
    </p>
<!--If current session is equal to the User Account Id -display the following options . Display
this option for each post -->
    <% if session[:user_id] == @user.id %>
      <%= link_to 'Edit Post', edit_post_path(post), :id => "editPost" %>
    <% end %>
  </div>
<% end %>

<!--If current session is equal to the User Account Id -display the following options  -->
<% if session[:user_id] == @user.id %>
  <%= link_to "Create Post", new_post_path,:id => "createPost" %>
  <%= link_to "Delete Account", users_path, :id => "deleteAccount", method: :delete %>
<% end %>
<%=image_tag("Salt.png", :class => "shaker") %>